### ISSUE TITLE
scope -> Battle.all.with_results returns same as Battle.all

### ISSUE THREAD

**Issue by jaredmurphy** [jaredmurphy/open_source_champ_api#2]
@bryanmytko 
First and most importantly, Rachel really likes the turtle sticker you made. 

Second, my scope in the Battle.rb model file called with_results does not grab the winner and loser's information as intended. Any advice would be dope.

Relevant files - Models/Battle.rb and Controllers/api/v1/battles_controller.rb

Thanks.

**Comment by jaredmurphy** [comment]
I figured out the the scope I was using doesn't load the additional queries for winner and loser immediately.
```
scope :with_results, -> { includes(:winner, :loser) }
```

Also found a way to handle this in the controller:
```
Battle.all.to_json(include: [:winner, :loser])
```

But I'd rather include this logic in the model. Having trouble getting it work for now.

**Comment by bryanmytko** [comment]
:tarf:
